version: '3'
services:
  web:
    image: dockersetup
    ports:
      - "3500:3500"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - data-volume:/var/lib/mysql
volumes:
  data-volume:
    